name: async_button_builder
description: A builder to wrap around buttons that handles loading, disabled,
  error and succes states
version: 3.0.0+2
homepage: https://github.com/Nolence/async_button/tree/main/packages/async_button_builder

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0

flutter: null
